// Code generated by protoc-gen-go. DO NOT EDIT.
// source: messages.proto

/*
Package psk is a generated protocol buffer package.

It is generated from these files:
	messages.proto

It has these top-level messages:
	KGRequest
	KGResponse
*/
package psk

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type KGRequest struct {
	PeerGroup        []byte `protobuf:"bytes,1,req,name=peer_group" json:"peer_group,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *KGRequest) Reset()                    { *m = KGRequest{} }
func (m *KGRequest) String() string            { return proto.CompactTextString(m) }
func (*KGRequest) ProtoMessage()               {}
func (*KGRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *KGRequest) GetPeerGroup() []byte {
	if m != nil {
		return m.PeerGroup
	}
	return nil
}

type KGResponse struct {
	KeyMaterial      []byte  `protobuf:"bytes,1,opt,name=key_material" json:"key_material,omitempty"`
	ErrorDetail      *string `protobuf:"bytes,2,opt,name=error_detail" json:"error_detail,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *KGResponse) Reset()                    { *m = KGResponse{} }
func (m *KGResponse) String() string            { return proto.CompactTextString(m) }
func (*KGResponse) ProtoMessage()               {}
func (*KGResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *KGResponse) GetKeyMaterial() []byte {
	if m != nil {
		return m.KeyMaterial
	}
	return nil
}

func (m *KGResponse) GetErrorDetail() string {
	if m != nil && m.ErrorDetail != nil {
		return *m.ErrorDetail
	}
	return ""
}

func init() {
	proto.RegisterType((*KGRequest)(nil), "psk.KGRequest")
	proto.RegisterType((*KGResponse)(nil), "psk.KGResponse")
}

func init() { proto.RegisterFile("messages.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 130 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x14, 0xca, 0xb1, 0x0a, 0xc2, 0x30,
	0x10, 0x06, 0x60, 0x52, 0xa7, 0x1e, 0xc1, 0x21, 0x38, 0x64, 0x33, 0x74, 0xca, 0xe4, 0xec, 0x1b,
	0x38, 0xb8, 0xf9, 0x02, 0x21, 0xe0, 0x4f, 0x29, 0x6d, 0xbd, 0xf3, 0x2e, 0x1d, 0x7c, 0x7b, 0xc9,
	0xfa, 0xf1, 0xd1, 0x79, 0x87, 0x59, 0x9d, 0x61, 0x37, 0x51, 0x6e, 0x1c, 0x4e, 0x62, 0xeb, 0x74,
	0xa5, 0xf1, 0xf9, 0x78, 0xe1, 0x7b, 0xc0, 0x5a, 0x08, 0x44, 0x02, 0x68, 0x99, 0x95, 0x0f, 0x89,
	0x2e, 0x0d, 0xd9, 0x4f, 0x77, 0xa2, 0x1e, 0x4c, 0xf8, 0x63, 0x08, 0x17, 0xf2, 0x2b, 0x7e, 0x65,
	0xaf, 0x0d, 0xba, 0xd4, 0x2d, 0xba, 0xe4, 0xb2, 0xef, 0x0a, 0x55, 0xd6, 0xf2, 0x46, 0xab, 0xcb,
	0x16, 0x87, 0xe4, 0xf2, 0xf8, 0x0f, 0x00, 0x00, 0xff, 0xff, 0xca, 0x32, 0x53, 0x02, 0x70, 0x00,
	0x00, 0x00,
}
