// Code generated by protoc-gen-go. DO NOT EDIT.
// source: rpc.proto

package tao

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

type RPCRequest struct {
	Data             []byte  `protobuf:"bytes,1,opt,name=data" json:"data,omitempty"`
	Size             *int32  `protobuf:"varint,2,opt,name=size" json:"size,omitempty"`
	Policy           *string `protobuf:"bytes,3,opt,name=policy" json:"policy,omitempty"`
	Time             *int64  `protobuf:"varint,4,opt,name=time" json:"time,omitempty"`
	Expiration       *int64  `protobuf:"varint,5,opt,name=expiration" json:"expiration,omitempty"`
	Issuer           []byte  `protobuf:"bytes,6,opt,name=issuer" json:"issuer,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *RPCRequest) Reset()                    { *m = RPCRequest{} }
func (m *RPCRequest) String() string            { return proto.CompactTextString(m) }
func (*RPCRequest) ProtoMessage()               {}
func (*RPCRequest) Descriptor() ([]byte, []int) { return fileDescriptor8, []int{0} }

func (m *RPCRequest) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

func (m *RPCRequest) GetSize() int32 {
	if m != nil && m.Size != nil {
		return *m.Size
	}
	return 0
}

func (m *RPCRequest) GetPolicy() string {
	if m != nil && m.Policy != nil {
		return *m.Policy
	}
	return ""
}

func (m *RPCRequest) GetTime() int64 {
	if m != nil && m.Time != nil {
		return *m.Time
	}
	return 0
}

func (m *RPCRequest) GetExpiration() int64 {
	if m != nil && m.Expiration != nil {
		return *m.Expiration
	}
	return 0
}

func (m *RPCRequest) GetIssuer() []byte {
	if m != nil {
		return m.Issuer
	}
	return nil
}

type RPCResponse struct {
	Data             []byte  `protobuf:"bytes,1,opt,name=data" json:"data,omitempty"`
	Policy           *string `protobuf:"bytes,2,opt,name=policy" json:"policy,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *RPCResponse) Reset()                    { *m = RPCResponse{} }
func (m *RPCResponse) String() string            { return proto.CompactTextString(m) }
func (*RPCResponse) ProtoMessage()               {}
func (*RPCResponse) Descriptor() ([]byte, []int) { return fileDescriptor8, []int{1} }

func (m *RPCResponse) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

func (m *RPCResponse) GetPolicy() string {
	if m != nil && m.Policy != nil {
		return *m.Policy
	}
	return ""
}

func init() {
	proto.RegisterType((*RPCRequest)(nil), "tao.RPCRequest")
	proto.RegisterType((*RPCResponse)(nil), "tao.RPCResponse")
}

func init() { proto.RegisterFile("rpc.proto", fileDescriptor8) }

var fileDescriptor8 = []byte{
	// 157 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x5c, 0xcd, 0x4f, 0xaa, 0xc2, 0x30,
	0x10, 0xc7, 0x71, 0xf2, 0xfa, 0x07, 0x32, 0xaf, 0x74, 0x91, 0x55, 0x96, 0xa1, 0xab, 0x80, 0xe0,
	0x25, 0xbc, 0x80, 0xf4, 0x06, 0xa1, 0xce, 0x62, 0x44, 0x3b, 0x31, 0x33, 0x05, 0xf5, 0xf4, 0x92,
	0x6e, 0x04, 0x97, 0x33, 0x3f, 0xf8, 0x7e, 0xc0, 0x96, 0xbc, 0x1c, 0x73, 0x61, 0x65, 0xd7, 0x68,
	0xe2, 0xe9, 0x0a, 0x30, 0x9f, 0x4f, 0x33, 0x3e, 0x36, 0x14, 0x75, 0x03, 0xb4, 0x97, 0xa4, 0xc9,
	0x9b, 0x60, 0xe2, 0x50, 0x2f, 0xa1, 0x37, 0xfa, 0xbf, 0x60, 0x62, 0xe7, 0x46, 0xe8, 0x33, 0xdf,
	0x68, 0x79, 0xf9, 0x26, 0x98, 0x68, 0xeb, 0xaa, 0x74, 0x47, 0xdf, 0x06, 0x13, 0x1b, 0xe7, 0x00,
	0xf0, 0x99, 0xa9, 0x24, 0x25, 0x5e, 0x7d, 0xb7, 0xff, 0x46, 0xe8, 0x49, 0x64, 0xc3, 0xe2, 0xfb,
	0xda, 0x9b, 0x0e, 0xf0, 0xbf, 0x5b, 0x92, 0x79, 0x15, 0xfc, 0xc1, 0xbe, 0xf9, 0xca, 0xd9, 0x4f,
	0x00, 0x00, 0x00, 0xff, 0xff, 0x65, 0xd0, 0x78, 0xe4, 0xa9, 0x00, 0x00, 0x00,
}
